# Generated by Django 4.2.7 on 2023-11-15 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=200)),
                ('breed', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('vaccine_status', models.CharField(blank=True, max_length=200, null=True)),
                ('caretaker', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(max_length=600)),
                ('allow_notifs', models.BooleanField(default=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('listed', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], max_length=50)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('available', 'available'), ('withdrawn', 'withdrawn'), ('adopted', 'adopted')], default='listed', max_length=10)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='pet_profile/')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='accounts.shelter')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=50)),
                ('description', models.CharField(max_length=600)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending'), ('denied', 'denied'), ('withdrawn', 'withdrawn')], default='pending', max_length=50)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.seeker')),
            ],
        ),
    ]
