# Generated by Django 4.2.7 on 2023-11-15 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0001_initial'),
        ('pet', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read_status', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('comment', 'comment'), ('application', 'application'), ('application_comment', 'application_comment')], default='application', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notification.notification')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_notifications', to='comment.comment')),
            ],
            bases=('notification.notification',),
        ),
        migrations.CreateModel(
            name='ApplicationNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notification.notification')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_notifications', to='pet.application')),
            ],
            bases=('notification.notification',),
        ),
        migrations.CreateModel(
            name='ApplicationCommentNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notification.notification')),
                ('application_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_comment_notifications', to='comment.applicationcomment')),
            ],
            bases=('notification.notification',),
        ),
    ]
